# Build settings
org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
#org.gradle.logging.level=debug

# plugin versions are in buildSrc/gradle.properties #

liblib.mod_name=LibrarianLib
liblib.mod_description=An extensive collection of tools, utilities, and frameworks.

# minecraft versions
# see: https://fabricmc.net/versions.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
fabric_loader_version=0.16.10
neoforge_version = 21.1.84
yarn_mappings_patch_neoforge_version = 1.21+build.4

# Liblib versions
mod_version=5.0.0
release.curseforge.type=alpha
release.modrinth.type=ALPHA

# Library versions
architectury_api_version = 13.0.8
fabric_api_version=0.115.3+1.21.1
fabric_kotlin_version=1.12.3+kotlin.2.0.21
release.modrinth.flk_version_id=476dzMG5

kotlin_for_forge_version=5.4.0

fabric.dependencies.fabricapi=>=0.115.3+1.21.1
fabric.dependencies.fabricloader=>=0.16.10
fabric.dependencies.minecraft=1.21.x
fabric.dependencies.flk=>=1.12.3+kotlin.2.0.21

neoforge.dependencies.neoforge=[21.1,)
neoforge.dependencies.minecraft=[1.21.1,)
neoforge.dependencies.kotlinforforge=[5.4,)

auto_service_ksp_version=1.2.0
