package com.teamwizardry.librarianlib.core.common

import com.teamwizardry.librarianlib.core.LibrarianLib
import com.teamwizardry.librarianlib.features.config.ConfigDevOnly
import com.teamwizardry.librarianlib.features.config.ConfigProperty
import com.teamwizardry.librarianlib.features.config.ConfigPropertyBoolean
import com.teamwizardry.librarianlib.features.config.ConfigPropertyInt
import net.minecraftforge.common.config.Configuration

object LibLibConfig {
    @JvmStatic
    @ConfigProperty(Configuration.CATEGORY_CLIENT, "Controls whether LibLib's shaders are used. If you're using the GLSL Shaders mod and are having graphical troubles with visuals, you may want to turn this off.",
            configId = LibrarianLib.MODID)
    var shaders: Boolean = false

    @JvmStatic
    @ConfigDevOnly
    @ConfigProperty(Configuration.CATEGORY_CLIENT, "Controls whether LibLib autogenerates json.",
            configId = LibrarianLib.MODID)
    var generateJson = true

    @JvmStatic
    @ConfigDevOnly
    @ConfigProperty(Configuration.CATEGORY_CLIENT, "Controls whether LibLib's autogenerated json is compressed.",
            configId = LibrarianLib.MODID)
    var prettyJsonSerialization = true

    @JvmStatic
    @ConfigProperty(Configuration.CATEGORY_GENERAL, "Only require one bonemeal to grow LibrarianLib saplings.",
            configId = LibrarianLib.MODID)
    var oneBonemeal = false

    @JvmStatic
    @ConfigProperty(Configuration.CATEGORY_CLIENT, "The maximum amount of particles that can exist at a time from the particle system.",
            configId = LibrarianLib.MODID)
    var maxParticleCount = 10000
}
