package com.teamwizardry.librarianlib.core.common

import com.teamwizardry.librarianlib.core.LibrarianLib
import com.teamwizardry.librarianlib.features.config.ConfigPropertyBoolean
import com.teamwizardry.librarianlib.features.config.ConfigPropertyInt
import net.minecraftforge.common.config.Configuration

object LibLibConfig {
    @JvmStatic
    @ConfigPropertyBoolean(LibrarianLib.MODID, Configuration.CATEGORY_CLIENT, "shaders", "Controls whether LibLib's shaders are used. If you're using the GLSL Shaders mod and are having graphical troubles with visuals, you may want to turn this off.", false)
    var useShaders: Boolean = false

    @JvmStatic
    @ConfigPropertyBoolean(LibrarianLib.MODID, Configuration.CATEGORY_CLIENT, "generate_json", "Controls whether LibLib autogenerates json.", true, true)
    var generateJson = true

    @JvmStatic
    @ConfigPropertyBoolean(LibrarianLib.MODID, Configuration.CATEGORY_CLIENT, "pretty_json_serialization", "Controls whether LibLib's autogenerated json is compressed.", true, true)
    var prettyJsonSerialization = true

    @JvmStatic
    @ConfigPropertyBoolean(LibrarianLib.MODID, Configuration.CATEGORY_GENERAL, "one_bonemeal", "Only require one bonemeal to grow LibrarianLib saplings.", false)
    var oneBonemeal = false

    @JvmStatic
    @ConfigPropertyInt(LibrarianLib.MODID, Configuration.CATEGORY_CLIENT, "maximum_particle_count", "The maximum amount of particles that can exist at a time from the particle system.", 10000)
    var maxParticleCount = 10000
}
